name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 請將下方的 YOUR_HF_USERNAME 與 YOUR_SPACE_NAME 改成你實際的 Hugging Face 帳號與空間名稱
          git push --force https://bvbnjghui:$HF_TOKEN@huggingface.co/spaces/bvbnjghui/voice-to-text master
